# Generated by Django 5.1.2 on 2024-10-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(default='У этого вида работ нет описания'),
        ),
    ]
