# Generated by Django 5.1.2 on 2024-10-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0002_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
