# Generated by Django 5.1.2 on 2024-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0004_alter_space_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='space',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
