# Generated by Django 5.1.2 on 2024-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0005_alter_space_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='fundraising',
            field=models.IntegerField(blank=True, default=56790, null=True),
        ),
    ]
