# Generated by Django 5.1.2 on 2024-10-24 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0006_alter_application_fundraising'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Reconstruction',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='application',
            new_name='reconstruction',
        ),
        migrations.AlterUniqueTogether(
            name='space',
            unique_together={('reconstruction', 'work')},
        ),
        migrations.AlterModelTable(
            name='reconstruction',
            table='reconstruction',
        ),
    ]
