# Generated by Django 5.1.2 on 2024-10-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction_app', '0007_rename_application_reconstruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstruction',
            name='fundraising',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
