# Generated by Django 5.1.2 on 2024-10-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
