# Generated by Django 5.1.1 on 2024-11-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0002_alter_customuser_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='imageUrl',
            new_name='imageurl',
        ),
    ]
