# Generated by Django 5.1.2 on 2024-10-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0002_alter_work_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstruction',
            name='fundraising',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
